export interface MenBotData {
    id_menbot: string; // O number si prefieres, pero el JSON lo muestra numérico
    origen: string;
    tip_doc: string;
    num_doc: string;
    flag_doc: string;
    fec_flag_doc: string;
    pri_nombre: string;
    seg_nombre: string;
    pri_apellido: string;
    seg_apellido: string;
    sexo: string;
    fec_nacido: string;
    telefono_o: string;
    telefono_c: string;
    email: string | null;
    fec_doc: string;
    flag_pac: string;
    existe_pac: string;
    modificar_pac: string | null;
    cod_depto: string | null;
    remitente: string | null;
    cod_sede: string | null;
    cod_empresa: string | null;
    nom_empresa: string | null;
    cod_examen: string | null;
    desc_examen: string | null;
    fec_examen: string | null;
    exam_encontrado: string | null;
    examen_correcto: string | null;
    fec_sol_cita: string | null;
    flag_estado: string | null;
    fec_dispo_1: string | null;
    hor_dispo_1: string | null;
    sed_dispo_1: string | null;
    cod_agenda_1: string | null;
    cod_equipo_1: string | null;
    acepta_1: string | null;
    asigna_1: string | null;
    fec_flag_1: string | null;
    fec_dispo_2: string | null;
    hor_dispo_2: string | null;
    sed_dispo_2: string | null;
    cod_agenda_2: string | null;
    cod_equipo_2: string | null;
    acepta_2: string | null;
    asigna_2: string | null;
    fec_flag_2: string | null;
    fec_dispo_3: string | null;
    hor_dispo_3: string | null;
    sed_dispo_3: string | null;
    cod_agenda_3: string | null;
    cod_equipo_3: string | null;
    acepta_3: string | null;
    asigna_3: string | null;
    fec_flag_3: string | null;
    fec_dispo_4: string | null;
    hor_dispo_4: string | null;
    sed_dispo_4: string | null;
    cod_agenda_4: string | null;
    cod_equipo_4: string | null;
    acepta_4: string | null;
    asigna_4: string | null;
    fec_flag_4: string | null;
    fec_dispo_5: string | null;
    hor_dispo_5: string | null;
    sed_dispo_5: string | null;
    cod_agenda_5: string | null;
    cod_equipo_5: string | null;
    acepta_5: string | null;
    asigna_5: string | null;
    fec_flag_5: string | null;
    reinicar: string | null;
    contactar: string | null;
    fec_cita: string | null;
    hor_cita: string | null;
    sed_cita: string | null;
    mensaje: string | null;
    identificador: string | null;
    req_paciente_ct: string | null;
    req_citas: string | null;
    hora_dispo: string;
}
