import { StyleSheet } from 'react-native';

export const globalStyles = StyleSheet.create({
    container: { flex: 1, backgroundColor: '#f8fafc' },
    scrollContainer: { padding: 20 },
    inputGroup: { marginBottom: 15 },
    label: {
        fontSize: 14,
        fontWeight: '600',
        color: '#374151',
        marginBottom: 8
    },
    dropdown: {
        flexDirection: 'row',
        justifyContent: 'space-between',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 8,
        paddingHorizontal: 12,
        height: 50,
        backgroundColor: '#f9fafb',
    },
    input: {
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 8,
        paddingHorizontal: 12,
        height: 50,
        backgroundColor: '#f9fafb',
        fontSize: 15,
    },
    inputWithIcon: {
        flexDirection: 'row',
        alignItems: 'center',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 8,
        paddingHorizontal: 12,
        height: 50,
        backgroundColor: '#f9fafb',
    },
    inputFlex: { flex: 1, marginLeft: 10 },
    placeholder: { color: '#9ca3af', fontSize: 15 },
    radioContainer: { flexDirection: 'row', gap: 10 },
    radioButton: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
        justifyContent: 'center',
        borderWidth: 1,
        borderColor: '#e5e7eb',
        borderRadius: 8,
        height: 50,
        gap: 8,
    },
    radioActive: { borderColor: '#ff9900', backgroundColor: '#fff5e6' },
    circle: {
        width: 16,
        height: 16,
        borderRadius: 8,
        borderWidth: 1,
        borderColor: '#d1d5db',
    },
    circleActive: { backgroundColor: '#ff9900', borderColor: '#ff9900' },
    radioText: { fontSize: 13, color: '#374151' },
    textArea: { height: 100, textAlignVertical: 'top', paddingTop: 12 },
    iconLeft: { marginRight: 0 },
    iconRight: { marginLeft: 10 },
    button: {
        backgroundColor: '#ff9900',
        paddingVertical: 14,
        paddingHorizontal: 40,
        borderRadius: 30,
        alignSelf: 'flex-start',
        shadowColor: '#ff9900',
        shadowOpacity: 0.3,
        shadowRadius: 10,
        elevation: 5,
        marginTop: 10
    },
    buttonText: { color: '#fff', fontWeight: 'bold', fontSize: 18 },
    inputError: { borderColor: '#ef4444' },
});
